2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Current SDK version is 0.15.11
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Configure stats pid to 3410152
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Loading settings from /home/augusto/.config/wandb/settings
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Loading settings from /home/augusto/symbolic/wandb/settings
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'avaliation.py', 'program_abspath': '/home/augusto/symbolic/avaliation.py', 'program': 'avaliation.py'}
2023-10-03 13:21:09,787 INFO    MainThread:3410152 [wandb_init.py:_log_setup():528] Logging user logs to /home/augusto/symbolic/wandb/run-20231003_132109-wn8w0s04/logs/debug.log
2023-10-03 13:21:09,788 INFO    MainThread:3410152 [wandb_init.py:_log_setup():529] Logging internal logs to /home/augusto/symbolic/wandb/run-20231003_132109-wn8w0s04/logs/debug-internal.log
2023-10-03 13:21:09,788 INFO    MainThread:3410152 [wandb_init.py:init():568] calling init triggers
2023-10-03 13:21:09,788 INFO    MainThread:3410152 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {}
2023-10-03 13:21:09,788 INFO    MainThread:3410152 [wandb_init.py:init():618] starting backend
2023-10-03 13:21:09,788 INFO    MainThread:3410152 [wandb_init.py:init():622] setting up manager
2023-10-03 13:21:09,789 INFO    MainThread:3410152 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-10-03 13:21:09,790 INFO    MainThread:3410152 [wandb_init.py:init():628] backend started and connected
2023-10-03 13:21:09,793 INFO    MainThread:3410152 [wandb_init.py:init():720] updated telemetry
2023-10-03 13:21:09,794 INFO    MainThread:3410152 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-10-03 13:21:10,279 INFO    MainThread:3410152 [wandb_run.py:_on_init():2220] communicating current version
2023-10-03 13:21:10,370 INFO    MainThread:3410152 [wandb_run.py:_on_init():2229] got version response 
2023-10-03 13:21:10,370 INFO    MainThread:3410152 [wandb_init.py:init():804] starting run threads in backend
2023-10-03 13:21:11,441 INFO    MainThread:3410152 [wandb_run.py:_console_start():2199] atexit reg
2023-10-03 13:21:11,442 INFO    MainThread:3410152 [wandb_run.py:_redirect():2054] redirect: wrap_raw
2023-10-03 13:21:11,442 INFO    MainThread:3410152 [wandb_run.py:_redirect():2119] Wrapping output streams.
2023-10-03 13:21:11,442 INFO    MainThread:3410152 [wandb_run.py:_redirect():2144] Redirects installed.
2023-10-03 13:21:11,442 INFO    MainThread:3410152 [wandb_init.py:init():845] run started, returning control to user process
2023-10-03 13:21:11,443 INFO    MainThread:3410152 [wandb_run.py:_config_callback():1324] config_cb None None {'trl_ppo_trainer_config': {'task_name': None, 'model_name': 'augustocsc/gpt-base', 'steps': 20000, 'learning_rate': 1.41e-05, 'adap_kl_ctrl': True, 'init_kl_coef': 0.2, 'kl_penalty': 'kl', 'target': 6, 'horizon': 10000, 'gamma': 1, 'lam': 0.95, 'cliprange': 0.2, 'cliprange_value': 0.2, 'vf_coef': 0.1, 'batch_size': 256, 'forward_batch_size': None, 'mini_batch_size': 8, 'backward_batch_size': 8, 'gradient_accumulation_steps': 1, 'ppo_epochs': 4, 'remove_unused_columns': True, 'log_with': 'wandb', 'tracker_project_name': 'trl', 'max_grad_norm': None, 'seed': 0, 'optimize_cuda_cache': False, 'early_stopping': False, 'target_kl': 0.1, 'compare_steps': 1, 'ratio_threshold': 10.0, 'use_score_scaling': False, 'use_score_norm': False, 'score_clip': None, 'total_ppo_epochs': 79}}
2023-10-03 13:21:16,263 WARNING MsgRouterThr:3410152 [router.py:message_loop():77] message_loop has been closed
